version: '3.8'

services:
  netmonitor:
    build: .
    container_name: netmonitor
    network_mode: host
    privileged: true    
    stdin_open: true 
    tty: true      
    volumes:
      - .:/app
    environment:
      - TERM=xterm-256color